In [2]:
import numpy as np

### Problem 1

In [4]:
#Find the inverse of the matrix (if it exists):
A = np.array([[3,4],[2,5]])

#Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    #Find the inverse of matrix A
    A_inv = np.linalg.inv(A)
print("The inverse of matrix A:\n",A_inv)

The inverse of matrix A:
 [[ 0.71428571 -0.57142857]
 [-0.28571429  0.42857143]]


### Problem 2

In [6]:
#Solve the system of equations
#Coefficient matrix
A = np.array([[2,3],[4,-1]])
#Constant vector
b = np.array([7,5])


solution = np.linalg.solve(A, b)
print("solution for [x, y]:\n",solution)

solution for [x, y]:
 [1.57142857 1.28571429]


### Problem 3

In [8]:
#Given the matrix
B = np.array([[1,2,3],[0,1,4],[5,6,0]])
#Calculate its inverse (if possible).

#Check if matrix B is invertible (determinant should not be zero)
det_B = np.linalg.det(B)
if det_B == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    #Find the inverse of matrix B
    B_inv = np.linalg.inv(B)
print("The inverse of matrix B:\n",B_inv)

The inverse of matrix B:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


### Problem 4

In [10]:
#Solve the system of equations using matrix inverse:
A = np.array([[1,1,1],[2,5,1],[2,3,8]])
#Constant vector
b = np.array([6,-4,9])

# Solve for x using matrix inverse
if np.linalg.det(A) != 0:
    x = np.linalg.inv(A).dot(b)
    print("Solution for [x, y, z]:\n",x)
else:
    print("Matrix A is not invertible, no unique solution.")

Solution for [x, y, z]:
 [10.84210526 -5.21052632  0.36842105]


### Problem 5

In [12]:
#A system of linear equations is given by the following matrix equation:
A = np.array([[4,-1,0],[3,5,2],[-2,4,1]])
b = np.array([5,6,2])

x = np.linalg.solve(A, b)
print("Solution vector x:\n",x)

Solution vector x:
 [  2.6   5.4 -14.4]
